spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/coding_tinder?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
server:
  port: 8082
  servlet:
    context-path: /api
