spring:
  profiles:
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coding_tinder?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  session:
    timeout: 86400
    store-type: redis
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml
  plus:
    global-config:
      db-config:
        id-type: auto

server:
  port: 8081
  servlet:
    context-path: /api